# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Test

on:
  push:
  pull_request:

jobs:
  test:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    name: Tests
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1

    - name: Install dependencies
      run: npm install

    - name: Validate Schemas
      run: |
        npm run validate:actions
        npm run validate:filters
