# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Test

on:
  push:
    branches:
      - develop
      - master
  pull_request: null

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Nodejs
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        cache: npm

    - name: Install dependencies
      run: |
        npm ci

    - name: Validate Schemas
      run: |
        npm exec -- npm-run-all 'validate:**'
