# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Test

on:
  push: null
  pull_request:
    branches:
      - develop
      - master

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - name: Install Nodejs
      uses: actions/setup-node@v3
      with:
        node-version: 16
    
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        npm ci

    - name: Validate Schemas
      run: |
        npm run 'validate:**'
